version: '3'

services:
  bot:
    image: ghcr.io/kylmakalle/blogger-bot:latest
    restart: always
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    environment:
      BOT_TOKEN: $BOT_TOKEN
      SENTRY_URL: $SENTRY_URL
